name: Custom Rom Builder Samsung Galaxy A01/M01

on:
  push:
    branches:
      - main  # Change this to your desired branch
  workflow_dispatch:
    inputs:
      GSI:
        description: 'direct link for Gsi image '
        required: true
        default: 'https://sourceforge.net/projects/ancientrom/files/gsi/V7.3-Hotfix/AncientOS-T-Shield-v7.3-arm64_bgN-Steel-20231001.img.xz'        
      ARCH:
        description: 'Arm32 or Arm64'
        required: true
        default: '64'                
      NAME:
        description: 'Rom Name'
        required: true
        default: 'AncientOS_7.3_SDM439_ARM64_Gapps'                

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y zip xz-utils unzip p7zip-full wget
        
    - name: Preparing Files
      run: |
        wget https://sourceforge.net/projects/samsung-galaxy-a01-m01/files/custom_rom_builder_439.zip
        git clone https://github.com/SamsungSDM439/Custom-Rom-Builder-For-Samsung-Galaxy-A01-M01
        unzip custom_rom_builder_439.zip
        rm -r custom_rom_builder_439.zip

    - name: Downloading your GSI
      run: |
        wget -P "./temp" ${{ github.event.inputs.GSI }} 
        chmod 755 *
        chmod 755 ./bin/*

    - name: Building
      run: |
        ./arm${{ github.event.inputs.ARCH }}_git
        
    - name: Uploading The Zip
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.inputs.NAME }}   # Replace with a suitable name
        path: ./zip/Custom_Rom_SDM439.zip
